// <copyright file="PreValidationcra2a_roleCreate.cs" company="">
// Copyright (c) 2026 All Rights Reserved
// </copyright>
// <author></author>
// <date>4/5/2026 3:36:41 PM</date>
// <summary>Implements the PreValidationcra2a_roleCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;

namespace cngetich.recruitplugin
{

    /// <summary>
    /// PreValidationcra2a_roleCreate Plugin.
    /// </summary>    
    public class PreValidationcra2a_roleCreate : PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidationcra2a_roleCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information.</param>
        public PreValidationcra2a_roleCreate(string unsecure, string secure)
            : base(typeof(PreValidationcra2a_roleCreate))
        {

            // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// </remarks>
        protected override void ExecuteCdsPlugin(ILocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException(nameof(localContext));
            }
            // Obtain the tracing service
            ITracingService tracingService = localContext.TracingService;

            try
            {
                // Obtain the execution context from the service provider.  
                IPluginExecutionContext context = (IPluginExecutionContext)localContext.PluginExecutionContext;

                // Obtain the organization service reference for web service calls.  
                IOrganizationService currentUserService = localContext.CurrentUserService;

                if (context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity entity)
                {
                    if (entity.Attributes.Contains("cra2a_newcolumn") || string.IsNullOrWhiteSpace(entity["cra2a_newcolumn"]?.ToString()))
                    {
                        string name = entity.GetAttributeValue<string>("cra2a_newcolumn");
                        if (name == "Test" || name == "")
                            throw new InvalidPluginExecutionException(name == "Test" ? "Role name cannot be Test." : "Role name cannot be empty.");
                    }
                }
            }
            catch (InvalidPluginExecutionException)
            {
                // Rethrow so the custom message is shown to the user
                throw;
            }
            catch (Exception ex)
            {
                tracingService?.Trace("An error occurred executing Plugin cngetich.recruitplugin.PreValidationcra2a_roleCreate : {0}", ex.ToString());
                throw new InvalidPluginExecutionException("An unexpected error occurred: " + ex.Message);
            }
        }
    }
}
