// <copyright file="PreValidationaccountCreate.cs" company="">
// Copyright (c) 2026 All Rights Reserved
// </copyright>
// <author></author>
// <date>4/5/2026 1:08:58 PM</date>
// <summary>Implements the PreValidationaccountCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;

namespace cngetich.recruitplugin
{

    /// <summary>
    /// PreValidationaccountCreate Plugin.
    /// </summary>    
    public class PreValidationaccountCreate : PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidationaccountCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information.</param>
        public PreValidationaccountCreate(string unsecure, string secure)
            : base(typeof(PreValidationaccountCreate))
        {

            // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// </remarks>
        protected override void ExecuteCdsPlugin(ILocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException(nameof(localContext));
            }
            // Obtain the tracing service
            ITracingService tracingService = localContext.TracingService;

            try
            {
                // Obtain the execution context from the service provider.  
                IPluginExecutionContext context = (IPluginExecutionContext)localContext.PluginExecutionContext;

                // Obtain the organization service reference for web service calls.  
                IOrganizationService currentUserService = localContext.CurrentUserService;

                // TODO: Implement your custom Plug-in business logic.
                if (context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity entity)
                {
                    if (!entity.Attributes.Contains("name") || string.IsNullOrWhiteSpace(entity["name"]?.ToString()))
                    {
                        throw new InvalidPluginExecutionException("Account name is required.");
                    }
                    
                }
                
                if(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity accountEntity)
                {
                    if (accountEntity.Attributes.Contains("telephone1") && !string.IsNullOrWhiteSpace(accountEntity["telephone1"]?.ToString()))
                    {
                        string phoneNumber = accountEntity["telephone1"].ToString();
                        if (!System.Text.RegularExpressions.Regex.IsMatch(phoneNumber, @"^\d{10}$"))
                        {
                            throw new InvalidPluginExecutionException("Phone number must be 10 digits.");
                        }
                    }
                }

            }
            // Only throw an InvalidPluginExecutionException. Please Refer https://go.microsoft.com/fwlink/?linkid=2153829.
            catch (Exception ex)
            {
                tracingService?.Trace("An error occurred executing Plugin cngetich.recruitplugin.PreValidationaccountCreate : {0}", ex.ToString());
                throw new InvalidPluginExecutionException("An error occurred executing Plugin cngetich.recruitplugin.PreValidationaccountCreate .", ex);
            }
        }
    }
}
